####GATEWAY

###Gateway:GetAll:Books
POST http://localhost:9191/api/v1/books
Content-Type: application/json

{
  "httpMethod": "GET"
}

###GateWay:Filter:Books
POST http://localhost:9191/api/v1/books
Content-Type: application/json

{
  "httpMethod": "GET",
  "queryParams": {
    "name": ["Orgullo"],
    "author": ["Austen"]
  }
}

###Gateway:Create:Books
POST http://localhost:9191/api/v1/books
Content-Type: application/json

{
  "httpMethod": "POST",
  "body": {
    "name": "Satanás",
    "isbn":  "978-9584273543",
    "image": "https://m.media-amazon.com/images/I/51aLugneWML._SY342_.jpg",
    "author": "Mario Mendoza",
    "releaseYear": 2018,
    "language": "Español",
    "rate": 4.6,
    "available": true
  }
}

###Gateway:Update:Books
POST http://localhost:9191/api/v1/books/f6c0cc33-f8b4-4d1d-aeec-fd14d62621ad
Content-Type: application/json

{
  "httpMethod": "PUT",
  "body": {
    "name": "Orgullo y Prejuizio",
    "isbn":  "978-0141439518",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81bR4c6y5-L.jpg",
    "author": "Jane Austen",
    "releaseYear": 1813,
    "language": "Español",
    "rate": 4.6,
    "available": true
  }
}

###Gateway:Verify:Books
POST http://localhost:9191/api/v1/books/verify
Content-Type: application/json

{
  "httpMethod": "POST",
  "body": {
    "booksID": ["f6c0cc33-f8b4-4d1d-aeec-fd14d62621ad"]
  }
}

###Gateway:Request:Books
POST http://localhost:9191/api/v1/books/request
Content-Type: application/json

{
  "httpMethod": "POST",
  "body": {
    "booksID": ["0b711c65-d72d-4004-a573-3ed29133f065"]
  }
}

###Gateway:ChangeAvailability:Books
POST http://localhost:9191/api/v1/books/availability
Content-Type: application/json

{
  "httpMethod": "PATCH",
  "body": {
    "booksID": ["651ac4b6-f67f-4f64-a73e-4a864959be4f"]
  }
}

###Gateway:GetAll:Requests
POST http://localhost:9191/api/v1/requests
Content-Type: application/json

{
  "httpMethod": "GET"
}

###Gateway:Create:Requests
POST http://localhost:9191/api/v1/requests
Content-Type: application/json

{
  "httpMethod": "POST",
  "body": {
    "booksID": ["2544c72a-f397-48bb-86c8-76e76c01f1c3"]
  }
}

###Gateway:Create:Requests
POST http://localhost:9191/api/v1/requests/dbeb495a-1273-4473-bc5e-dea03a686d09
Content-Type: application/json

{
  "httpMethod": "DELETE"
}