########################
######## MS Books
########################

### Todos los libros
GET http://localhost:8082/api/v1/books
Content-Type: application/json

### Todos los libros
GET http://localhost:8082/api/v1/books?name=Orgullo
Content-Type: application/json

### Todos los libros
GET http://localhost:8082/api/v1/books?name=Cien
Content-Type: application/json

### Verificar: ShopCar
POST http://localhost:8082/api/v1/books/verify
Content-Type: application/json

{
  "booksID": [
    "c675c27e-1150-4360-b5ef-630797f6c08a"
  ]
}


### Create:Book
POST http://localhost:8082/api/v1/books
Content-Type: application/json

{
  "name": "Creacion el maravilloso libro",
  "isbn": "13123-13413-1234",
  "image": "url de imagen",
  "author": "author",
  "releaseYear": 2023,
  "language": "Spanisch",
  "rate": 3.4
}

### TODO: Delete:Book

###Update:Book
PUT http://localhost:8082/api/v1/books/6f22c294-5611-4806-8c53-a6e3531802ab
Content-Type: application/json

{
  "name": "Actualizado el maravilloso libro",
  "isbn": "13123-13413-1234",
  "image": "url de imagen",
  "author": "author",
  "releaseYear": 2023,
  "language": "Spanisch",
  "rate": 3.4,
  "available": true
}

### Compra:Books
POST http://localhost:8082/api/v1/books/request
Content-Type: application/json

{
  "booksID": [
    "5a436c89-a86f-42ca-9389-39d8842a20e2"
  ]
}

### ChangeAvailability:Book
PATCH http://localhost:8082/api/v1/books/availability
Content-Type: application/json

{
  "booksID": [
    "c675c27e-1150-4360-b5ef-630797f6c08a"
  ]
}

########################
######## MS Request
########################

###All:Request
GET http://localhost:8081/api/v1/requests
Content-Type: application/json

### Delete:Request
DELETE http://localhost:8081/api/v1/requests/ba62032c-bf30-4933-ad34-6857f68dbdae
Content-Type: application/json

###HealthCheck Request
GET http://localhost:8081/api/v1/request/check
Content-Type: application/json

### Crear Peitcion de Libros
POST http://localhost:8081/api/v1/requests
Content-Type: application/json

{
  "booksID": [
    "1b4405d6-7c42-4ec6-b232-9637442ac47c"
  ]
}