### Todos los libros
GET http://localhost:8082/api/v1/books
Content-Type: application/json

### Todos los libros
GET http://localhost:8082/api/v1/books?author=Gabriel
Content-Type: application/json

### Todos los libros
GET http://localhost:8082/api/v1/books?name=Cien
Content-Type: application/json

###HealthCheck Request
GET http://localhost:8081/api/v1/request
Content-Type: application/json

### Crear Peitcion de Libros
POST http://localhost:8081/api/v1/requests/create
Content-Type: application/json

{
  "booksID": ["e568e3f5-6d12-4b6e-a9ca-931872ad4d53"]
}

### Verificar: ShopCar
POST http://localhost:8082/api/v1/books/verify
Content-Type: application/json

{
  "booksID": ["7ea17b5e-e47f-4bfd-a085-b64508fe7ddb"]
}


### Todo: Create:Book

### TODO: Delete:Book

### TODO: Update:Book


### Compra:Books
POST http://localhost:8082/api/v1/books/request
Content-Type: application/json

{
  "booksID": ["7ea17b5e-e47f-4bfd-a085-b64508fe7ddb"]
}

###All:Request
GET http://localhost:8081/api/v1/requests/all
Content-Type: application/json

### Delete:Request
DELETE http://localhost:8081/api/v1/requests?requestUUID=cd16a22f-b359-4927-8bc9-73ddec3be46c
Content-Type: application/json

### ChangeAvailability:Book
PATCH http://localhost:8082/api/v1/books/availability
Content-Type: application/json

{
  "booksID": ["2c30e590-cd40-463f-a502-772671d6ccff"]
}

### Update:Books
PUT http://localhost:8082/api/v1/books?id=6f22c294-5611-4806-8c53-a6e3531802ab
Content-Type: application/json

{
  "name": "Actualizado el maravilloso libro",
  "isbn": "13123-13413-1234",
  "image": "url de imagen",
  "author": "author",
  "releaseYear": 2023,
  "language": "Spanisch",
  "rate": 3.4,
  "available": true
}