### Libros Filtrados
GET http://localhost:8082/api/v1/books/filterBy?author=Gabriel&name=Cien
Content-Type: application/json

### Todos los libros
GET http://localhost:8082/api/v1/books/all
Content-Type: application/json

###HealthCheck Request
GET http://localhost:8081/api/v1/request
Content-Type: application/json

### Crear Peitcion de Libros
POST http://localhost:8081/api/v1/requests/create
Content-Type: application/json

{
  "booksID": ["e568e3f5-6d12-4b6e-a9ca-931872ad4d53"]
}

### Verificar: ShopCar
POST http://localhost:8082/api/v1/books/verify
Content-Type: application/json

{
  "booksID": ["e3db8507-8cf5-48bd-bf67-1f007cb291d5"]
}




### Compra:Books
POST http://localhost:8082/api/v1/books/request
Content-Type: application/json

{
  "booksID": ["e3db8507-8cf5-48bd-bf67-1f007cb291d5"]
}

###All:Request
GET http://localhost:8081/api/v1/requests/all
Content-Type: application/json

### Delete:Request
DELETE http://localhost:8081/api/v1/requests?requestUUID=509d6448-13ef-4aed-b2d9-80cfe38f1033
Content-Type: application/json

###ChangeAvailability:Book
POST http://localhost:8082/api/v1/books/changeAvailability
Content-Type: application/json

{
  "booksID": ["b4da393f-54be-4407-b6f4-54199fd4299d"]
}
