server:
  port: 8082

spring:
  application:
    name: books
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/books
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: '5672'
  data:
    elasticsearch:
      repositories:
        enabled: true
        cluster-nodes: localhost:9200
        cluster-name: docker-cluster

rabbitmq:
  queue: sms_notification
  exchange: sms_exchange
  routingkey: sms_routingkey


management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c,b3_multi
    exporter:
      zipkin:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

