server:
  port: 8082

spring:
  application:
    name: books
  datasource:
    password: admin
    url: ${DB_URL}
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: '5672'
  data:
    elasticsearch:
      repositories:
        enabled: true
        cluster-nodes: ${ELASTIC_URL}
        cluster-name: docker-cluster
eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_URL}

