server:
  port: 8081

spring:
  application:
    name: requests
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5433/requests
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: '5672'
    username: guest
    password: guest

rabbitmq:
  in:
    requests:
      queue: q.requests.creation
      exchange: sms_requests
  out:
    books:
      queue: q.books.availabilities
      exchange: sms_books
      routingkey: sms_books_routingkey


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c, b3_multi, b3
    exporter:
      zipkin:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


