server:
  port: 8081

spring:
  application:
    name: requests
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5433/requests
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: '5672'
    username: guest
    password: guest

rabbitmq:
  queue: sms_notification
  exchange: sms_exchange


management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c,b3_multi
    exporter:
      zipkin:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


