version: '3.8'

services:

  web:
    profiles: [ "deploy" ]
    container_name: web
    build:
      context: ..
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    networks:
      - unir
    depends_on:
      - db

  db:
    profiles: [ "deploy" ]
    container_name: db
    build:
      context: ..
      dockerfile: DockerfileUtil
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - unir


networks:
  unir:
    driver: bridge